#!/usr/bin/bash

resolveLink() {
  local NAME=$1

  if [ -L "$NAME" ]; then
    case "$OSTYPE" in
      darwin*|bsd*)
        # BSD style readlink behaves differently to GNU readlink
        # Have to manually follow links
        while [ -L "$NAME" ]; do
          NAME=$( cd $NAME && pwd -P ) ;
        done
        ;;
      *)
        # Assuming standard GNU readlink with -f for
        # canonicalize and follow
        NAME=$(readlink -f "$NAME")
        ;;
    esac
  fi

  echo "$NAME"
}

SCRIPT=$(resolveLink "$0")
DIR="$(dirname $SCRIPT)"
#echo "DIR=$DIR"

ARGS="$@"
JVM_ARGS=${JVM_ARGS:--Xmx2000M}
MAIN="org.apache.jena.fuseki.main.cmds.FusekiMainCmd"

if true
then
    CPF="$DIR"/rdf-abac.classpath
    if [ ! -e "$CPF" ]; then
	echo "Need to create the classpath file"
	echo "Ensure maven is up to date with the latest snapshots and then run"
	echo "( cd $DIR ;"
	echo "  mvn dependency:build-classpath \\"
	echo "     -DincludeScope=runtime -Dmdep.outputFile=$CPF )"
	exit 1
    fi
    CP="$(cat $CPF)"
    CP="$DIR/target/classes:$CP"

    ## echo "$CP" \
	##     | sed -e 's/:/\n/g' \
	##     | sed -e 's!^/home/afs/.m2/repo!Repo!g' \
	##     | grep -v '^Repo'

    exec java -cp "$CP" $JVM_ARGS $MAIN $ARGS
fi

JAR="$(echo $DIR/target/triple-abac-0.0.0-SNAPSHOT.jar)"
JAR_FUSEKI="$HOME/.m2/repo/org/apache/jena/jena-fuseki-server/4.5.0-SNAPSHOT/jena-fuseki-server-4.5.0-SNAPSHOT.jar"

exec java -cp "$JAR:$JAR_FUSEKI" $JVM_ARGS $MAIN $ARGS
